aws:
  region: ap-south-1
  s3:
    bucket-name: order-invoices-2025
  dynamodb:
    table-name: Orders
  sns:
    topic-arn: arn:aws:sns:ap-south-1:YOUR_ACCOUNT_ID:order-notify-topic

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
